[programs.localnet]
amplify = "6tdSxHkjBn6Da6PuF8snm1jeVtyXk67G5SFqNCxxK1B7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sholto/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
