[programs.localnet]
amplify = "5xJX49gW56EWkQJeBELE74TsQeNogtuR3DyHJGF69SoC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/jackliellcock/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
