[programs.localnet]
amplify = "7BFUYjtQA6wXd4WgGGFrDiZ8r2iXNSnDPKT8J2ZHs7Dw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/tristan/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
